# Generated by Django 3.1.1 on 2020-09-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('major', models.TextField()),
                ('phone_num', models.IntegerField()),
                ('body_temp', models.IntegerField()),
                ('update_time', models.DateTimeField(verbose_name='date published')),
                ('agree_check', models.BooleanField()),
            ],
        ),
    ]
