# Generated by Django 3.1.1 on 2020-09-15 05:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='body_temp',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='survey',
            name='major',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
