# Generated by Django 3.1.1 on 2020-09-15 05:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0002_auto_20200915_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
